name: Format

on:
  workflow_run:
    workflows: ["Test"]
    branches: ["main"]
    types: 
      - completed
  
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install black
      - run: |
          pip install nbqa
      - name: format
        run: make format
